export const IdentificationTypes = [
  "Birth Certificate",
  "Driver's License",
  "Medical Insurance Card/Policy",
  "Military ID Card",
  "National Identity Card",
  "Passport",
  "Resident Alien Card (Green Card)",
  "Social Security Card",
  "State ID Card",
  "Student ID Card",
  "Voter ID Card",
];

export const medicineCategories = [
  "Analgesic",
  "Antibiotic",
  "Antifungal",
  "Antiviral",
  "Antiseptic",
  "Antipyretic",
  "Anti-inflammatory",
  "Antacid",
  "Antiemetic",
  "Antihistamine",
  "Bronchodilator",
  "Cardiovascular",
  "Corticosteroid",
  "Diuretic",
  "Gastrointestinal",
  "Hormonal",
  "Immunosuppressant",
  "Neurological",
  "Psychotropic",
  "Respiratory",
  "Sedative",
  "Vaccine",
  "Vitamin and Mineral Supplement",
  "Dermatological",
  "Ophthalmic",
];
